const Data = [
    {
        id: 1,
        image: "https://i.pinimg.com/564x/c5/93/72/c593722993fbe4ef45540982ba3176d6.jpg",
        name: "Modern Salwar",
        color: "Red",
        price: 2500,
        dealOfTheDayPrice: 2200,
        brand: "Ethnic Wear Co.",
        outfit: "Salwar Kamij",
        description: "A stylish modern salwar perfect for any occasion.",
        rating: 4.5,
        reviewNumber: 150,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:18
    },
    {
        id: 2,
        image: "https://i.pinimg.com/originals/fb/7c/69/fb7c6958d892404059767ade28e89e0a.jpg",
        name: "Classic Denim",
        color: "Blue",
        price: 1200,
        dealOfTheDayPrice: 1000,
        brand: "Denim",
        outfit: "Jeans",
        description: "Comfortable and stylish classic denim jeans.",
        rating: 4.3,
        reviewNumber: 200,
        availability: "In stock",
        stock:12
    },
    {
        id: 3,
        image: "https://images.squarespace-cdn.com/content/v1/5c832b55af4683b3a857c8ef/1661117178118-KEEORYQ7O5WEVXFII5AQ/WhatsApp+Image+2022-08-21+at+1.30.32+PM.jpeg?format=1000w",
        name: "Sharara Salwar",
        color: "Green",
        price: 3200,
        dealOfTheDayPrice: 2900,
        brand: "Ethnic Wear Co.",
        outfit: "Salwar Kamij",
        description: "Elegant Sharara Salwar for festive occasions.",
        rating: 4.7,
        reviewNumber: 120,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:16
    },
    {
        id: 4,
        image: "https://i.pinimg.com/736x/51/03/18/5103180b30181fa8dec136bf19468e1e.jpg",
        name: "Chic Frock",
        color: "Yellow",
        price: 1600,
        dealOfTheDayPrice: 1400,
        brand: "Zara",
        outfit: "Frock",
        description: "Bright and chic frock for summer days.",
        rating: 4.4,
        reviewNumber: 180,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:10
    },
    {
        id: 5,
        image: "https://assets.ajio.com/medias/sys_master/root/20210906/NnzE/61362e1daeb269a2688ba45d/-473Wx593H-462910552-black-MODEL.jpg",
        name: "Casual Top",
        color: "Black",
        price: 1800,
        dealOfTheDayPrice: 1600,
        brand: "H&M",
        outfit: "Top",
        description: "Stylish casual top for everyday wear.",
        rating: 4.2,
        reviewNumber: 220,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 6,
        image: "https://banarasikargha.in/cdn/shop/products/DSC_0842_ce882a5d-a5ed-4445-a6ec-4eef2abfb4bb.jpg?v=1679306133",
        name: "Katan Sari",
        color: "Blue",
        price: 5300,
        dealOfTheDayPrice: 5000,
        brand: "Dhakeswari Bastralaya",
        outfit: "Saree",
        description: "Luxurious Katan Sari for special occasions.",
        rating: 4.8,
        reviewNumber: 90,
        availability: "In stock",
        stock:8
    },
    {
        id: 7,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyfZtYJYGHoT5EUF_I87bbeSW3aTJ3fSrE-g&s",
        name: "Black Jeans",
        color: "Black",
        price: 1100,
        dealOfTheDayPrice: 950,
        brand: "Denim",
        outfit: "Jeans",
        description: "Versatile black jeans for a sleek look.",
        rating: 4.1,
        reviewNumber: 130,
        availability: "In stock",
        stock:8
    },
    {
        id: 8,
        image: "https://www.karagiri.com/cdn/shop/products/salwar-suit-purple-salwar-suit-silk-saree-online-32354427011265.jpg?v=1652947157&width=533",
        name: "Traditional Salwar",
        color: "Purple",
        price: 2400,
        dealOfTheDayPrice: 2100,
        brand: "Ethnic Wear Co.",
        outfit: "Salwar Kamij",
        description: "Classic traditional salwar for festive events.",
        rating: 4.5,
        reviewNumber: 100,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:13
    },
    {
        id: 9,
        image: "https://ashbhav.com/cdn/shop/files/1_23e6d286-8a3a-4752-a089-11830d3a32f3.jpg?v=1698551204",
        name: "Pink Lehenga",
        color: "Pink",
        price: 6400,
        dealOfTheDayPrice: 6000,
        brand: "Forever 21",
        outfit: "Lehenga",
        description: "Gorgeous pink lehenga for weddings and parties.",
        rating: 4.9,
        reviewNumber: 85,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:9
    },
    {
        id: 10,
        image: "https://i8.amplience.net/i/jpl/jd_454913_a?v=1",
        name: "Sporty Top",
        color: "Gray",
        price: 1300,
        dealOfTheDayPrice: 1100,
        brand: "Nike",
        outfit: "Top",
        description: "Comfortable sporty top for active wear.",
        rating: 4.3,
        reviewNumber: 240,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:4
    },
    {
        id: 11,
        image: "https://www.zeelclothing.com/media/catalog/product/cache/1a663af2519e1158a3f1f53631c1a350/1/2/1207_52972116623_o_-_copy_1.jpg",
        name: "Festive Sari",
        color: "Orange",
        price: 3000,
        dealOfTheDayPrice: 2700,
        brand: "Dhakeswari Bastralaya",
        outfit: "Saree",
        description: "Vibrant festive sari for celebrations.",
        rating: 4.6,
        reviewNumber: 110,
        availability: "In stock",
        stock:15
    },
    {
        id: 12,
        image: "https://resources.indianclothstore.com/resources/productimages/800326082022-Sea-Green-Net-A-Line-Lehenga-Choli.jpg",
        name: "Sea Green Lehenga",
        color: "Sea Green",
        price: 8800,
        dealOfTheDayPrice: 8300,
        brand: "Ethnic Wear Co.",
        outfit: "Lehenga",
        description: "Stunning sea green lehenga for special events.",
        rating: 4.8,
        reviewNumber: 95,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:10
    },
    {
        id: 13,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs0c8ecg4QaCrJJT-nHL2XqrlVLN-LbYkJicHAgd8BmU_gF30yCc_sYbVf9qnGGaEzwQM&usqp=CAU",
        name: "Elegant Sari",
        color: "White",
        price: 3700,
        dealOfTheDayPrice: 3400,
        brand: "Dhakeswari Bastralaya",
        outfit: "Saree",
        description: "Sophisticated elegant sari for formal events.",
        rating: 4.7,
        reviewNumber: 100,
        availability: "In stock",
        stock:20
    },
    {
        id: 14,
        image: "https://shegowns.com/cdn/shop/products/VNeckLongSleevesBurgundyTeaLengthPromDresses_LongSleevesBurgundyTeaLengthFormalEveningDresses_600x.jpg?v=1642131900",
        name: "Party Frock",
        color: "Blue",
        price: 2600,
        dealOfTheDayPrice: 2300,
        brand: "Zara",
        outfit: "Frock",
        description: "Stylish party frock for evening gatherings.",
        rating: 4.5,
        reviewNumber: 140,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 15,
        image: "https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/800x1200/a12781a7f2ccb3d663f7fd01e1bd2e4e/e/m/embroidered-silk-teal-green-saree-sarv145314-1.jpg",
        name: "Silk Sari",
        color: "Green",
        price: 3300,
        dealOfTheDayPrice: 3000,
        brand: "Dhakeswari Bastralaya",
        outfit: "Saree",
        description: "Elegant silk sari for traditional functions.",
        rating: 4.6,
        reviewNumber: 125,
        availability: "In stock",
        stock:20
    },
    {
        id: 16,
        image: "https://rukminim2.flixcart.com/image/850/1000/l3q7jww0/top/r/y/e/xl-flipkart-top-eva-yellow-dream-beauty-fashion-original-images739yxdwqgt.jpeg?q=90&crop=false",
        name: "Vintage Top",
        color: "Yellow",
        price: 1800,
        dealOfTheDayPrice: 1500,
        brand: "H&M",
        outfit: "Top",
        description: "Charming vintage top with a modern twist.",
        rating: 4.3,
        reviewNumber: 200,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 17,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/jean/8/1/d/34-udwj0036-united-denim-original-imaghauhfxhknykz.jpeg?q=90&crop=false",
        name: "Retro Jeans",
        color: "Brown",
        price: 1700,
        dealOfTheDayPrice: 1500,
        brand: "Denim",
        outfit: "Jeans",
        description: "Retro style jeans for a vintage look.",
        rating: 4.2,
        reviewNumber: 110,
        availability: "In stock",
        stock:8
    },
    {
        id: 18,
        image: "https://5.imimg.com/data5/ANDROID/Default/2022/11/LO/YN/BX/144274768/product-jpeg.jpg",
        name: "Gorgeous Black Saree",
        color: "Black",
        price: 6200,
        dealOfTheDayPrice: 5900,
        brand: "Ethnic Wear Co.",
        outfit: "Saree",
        description: "Stunning black saree for formal events.",
        rating: 4.9,
        reviewNumber: 85,
        availability: "In stock",
        stock:13
    },
    {
        id: 19,
        image: "https://m.media-amazon.com/images/I/91w6ETbxyfL._AC_SL1500_.jpg",
        name: "Floral Frock",
        color: "White",
        price: 1200,
        dealOfTheDayPrice: 1000,
        brand: "Forever 21",
        outfit: "Frock",
        description: "Light and breezy floral frock for summer.",
        rating: 4.1,
        reviewNumber: 170,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 20,
        image: "https://rukminim2.flixcart.com/image/850/1000/xif0q/top/2/v/j/xs-top-ghather-red-me-craft-original-imagm2gcqxpprfaa.jpeg?q=90&crop=false",
        name: "Summer Top",
        color: "Red",
        price: 800,
        dealOfTheDayPrice: 700,
        brand: "Forever 21",
        outfit: "Top",
        description: "Bright summer top perfect for sunny days.",
        rating: 4.0,
        reviewNumber: 210,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 21,
        image: "https://images.indianweddingsaree.com/tr:w-395,q-80/AlternateView/1604009/A637055223365909527.jpg",
        name: "Luxury Sari",
        color: "Pink",
        price: 5200,
        dealOfTheDayPrice: 4900,
        brand: "Dhakeswari Bastralaya",
        outfit: "Saree",
        description: "Opulent luxury sari for grand occasions.",
        rating: 4.7,
        reviewNumber: 100,
        availability: "In stock",
        stock:14
    },
    {
        id: 22,
        image: "https://5.imimg.com/data5/SELLER/Default/2021/6/LJ/SJ/UK/130085995/bridal-lehenga-500x500.jpg",
        name: "Bridal Lehenga",
        color: "Maroon",
        price: 14900,
        dealOfTheDayPrice: 14000,
        brand: "Ethnic Wear Co.",
        outfit: "Lehenga",
        description: "Exquisite bridal lehenga for weddings.",
        rating: 5.0,
        reviewNumber: 50,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:5
    },
    {
        id: 23,
        image: "https://medias.utsavfashion.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/e/m/embroidered-georgette-abaya-style-suit-in-light-pink-v3-kch9210.jpg",
        name: "Elegant Salwar",
        color: "Pink",
        price: 2600,
        dealOfTheDayPrice: 2300,
        brand: "Ethnic Wear Co.",
        outfit: "Salwar Kamij",
        description: "Graceful and elegant salwar for special occasions.",
        rating: 4.6,
        reviewNumber: 130,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:20
    },
    {
        id: 24,
        image: "https://cdn.sareeka.com/image/cache/data2019/embroidered-cotton-churidar-salwar-kameez-in-white-128036-1000x1375.jpg",
        name: "Trendy Salwar",
        color: "White",
        price: 2400,
        dealOfTheDayPrice: 2100,
        brand: "Ethnic Wear Co.",
        outfit: "Salwar Kamij",
        description: "Trendy white salwar for modern women.",
        rating: 4.4,
        reviewNumber: 150,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:14
    },
    {
        id: 25,
        image: "https://www.lulus.com/images/product/xlarge/1678752_272986.jpg",
        name: "Trendy Top",
        color: "Blue",
        price: 1800,
        dealOfTheDayPrice: 1600,
        brand: "H&M",
        outfit: "Top",
        description: "Trendy blue top for casual wear.",
        rating: 4.2,
        reviewNumber: 190,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 26,
        image: "https://i.pinimg.com/originals/14/8a/ee/148aeed424f90680adcb63b8b0187668.jpg",
        name: "Casual Top",
        color: "Red",
        price: 1900,
        dealOfTheDayPrice: 1700,
        brand: "H&M",
        outfit: "Top",
        description: "Comfortable casual top for daily wear.",
        rating: 4.3,
        reviewNumber: 180,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
    {
        id: 27,
        image: "https://getethnic.com/wp-content/uploads/2021/11/blue-bridal-lehenga-wedding16.jpg",
        name: "Bridal Lehenga",
        color: "Blue",
        price: 17900,
        dealOfTheDayPrice: 17000,
        brand: "Ethnic Wear Co.",
        outfit: "Lehenga",
        description: "Magnificent blue bridal lehenga for the bride-to-be.",
        rating: 5.0,
        reviewNumber: 60,
        availability: "In stock",
        size: ["S",  "M",  "L"],
        stock:3
    },
    {
        id: 28,
        image: "https://www.jungle.lk/wp-content/uploads/2022/05/Zara-UK-Original-Strapless-Frock-Dress-Small-UK-8.jpg",
        name: "White Stripe Frock",
        color: "White",
        price: 2600,
        dealOfTheDayPrice: 2300,
        brand: "Zara",
        outfit: "Frock",
        description: "Chic white stripe frock for any occasion.",
        rating: 4.5,
        reviewNumber: 175,
        availability: "In stock",
        size: ["S", "M", "L"],
        stock:8
    },
];

export default Data;
